#24 Migrate to null-safety
YazeedAlKhalaf/Flutter_Installer pull request #27
Opened 2021-10-14 11:45 UTC by jxstxn1

Addressing Issue #24.
Successfully migrated the project to Null-Safety

Please let me know if I have to do further changes to get the Hacktoberfest Approval

2021-10-14 12:06 UTC, YazeedAlKhalaf commented
will try to check it later today.
thanks for the awesome contribution.

2021-10-14 12:09 UTC, jxstxn1 commented
No Problem
Thank you for your fast response

2021-10-14 13:32 UTC, yahu1031 requested changes
@jxstxn1 Just give them a **Try**. And maintain the style of your coding same everywhere.

2021-10-14 13:32 UTC, yahu1031 commented on lib/src/app/models/flutter_installer_api/app_release.mode.dart
>    final DownloadLinks downloadLinks;
can also make this nullable. It's okie if it works fine.

2021-10-14 13:32 UTC, yahu1031 commented on lib/src/app/models/flutter_installer_api/latest.model.dart
>    final Scripts scripts;
here too...

2021-10-14 13:32 UTC, yahu1031 commented on pubspec.yaml
> +  msix: ^2.3.0
[msix](https://pub.dev/packages/msix) config missing.

2021-10-14 13:32 UTC, yahu1031 commented on pubspec.yaml
>    window_size:
Better to start using [bitsdojo_window](https://pub.dev/packages/bitsdojo_window). We also have frameless windows there.

2021-10-14 13:37 UTC, jxstxn1 commented on pubspec.yaml
> +  msix: ^2.3.0
Thank you totally missed this. I can only test it on MacOS

2021-10-14 13:44 UTC, jxstxn1 commented on pubspec.yaml
>    window_size:
> [bitsdojo_window](https://pub.dev/packages/bitsdojo_window)

So which packages should I replace with bitsdojo_window?

2021-10-14 13:48 UTC, yahu1031 commented on pubspec.yaml
>    window_size:
`window_size`

2021-10-14 13:50 UTC, jxstxn1 commented on pubspec.yaml
>    window_size:
alright

2021-10-14 14:03 UTC, yahu1031 commented on pubspec.yaml
>    window_size:
not a primary thing but you can just play and see what you can do with it 😄

2021-10-14 14:13 UTC, jxstxn1 commented on pubspec.yaml
>    window_size:
Yes of course :)

2021-10-14 14:34 UTC, jxstxn1 commented
@yahu1031 Are you able to test it, because my System is telling me that my Developer Licence doesn't be the Licence which is used in the project.

2021-10-14 14:35 UTC, yahu1031 commented
lemme try

2021-10-14 15:04 UTC, yahu1031 commented
@jxstxn1 Better add missing return types for the code. and found this issue

```
Restarted application in 477ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building ValueListenableBuilder<Box<bool>>(dirty, state: _ValueListenableBuilderState<Box<bool>>#44d22):
'package:flutter/src/material/theme_data.dart': Failed assertion: line 350 pos 12: 'colorScheme?.brightness == null || brightness == null || colorScheme!.brightness == brightness': is not true.

The relevant error-causing widget was
ThemeModeBuilder
When the exception was thrown, this was the stack
#2      new ThemeData
#3      App.build.<anonymous closure>
#4      ThemeModeBuilder.build.<anonymous closure>.<anonymous closure>
#5      _ValueListenableBuilderState.build
#6      StatefulElement.build
#7      ComponentElement.performRebuild
#8      StatefulElement.performRebuild
#9      Element.rebuild
#10     ComponentElement._firstBuild
#11     StatefulElement._firstBuild
#12     ComponentElement.mount
...     Normal element mounting (7 frames)
#19     SingleChildWidgetElementMixin.mount
#20     Element.inflateWidget
#21     Element.updateChild
#22     ComponentElement.performRebuild
#23     _InheritedProviderScopeElement.performRebuild
#24     Element.rebuild
#25     ComponentElement._firstBuild
#26     ComponentElement.mount
#27     _InheritedProviderScopeElement.mount
...     Normal element mounting (7 frames)
#34     SingleChildWidgetElementMixin.mount
...     Normal element mounting (21 frames)
#55     Element.inflateWidget
#56     Element.updateChild
#57     RenderObjectToWidgetElement._rebuild
#58     RenderObjectToWidgetElement.mount
#59     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
#60     BuildOwner.buildScope
#61     RenderObjectToWidgetAdapter.attachToRenderTree
#62     WidgetsBinding.attachRootWidget
#63     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════
```

**EDIT(SOLUTION) :**
It is because when you have `colorScheme` property, you can't use `brightness` of a `ThemeData`. use brightness in `colorSheme`.

2021-10-14 15:14 UTC, yahu1031 commented
@jxstxn1 Sorry to tell you, this cannot be approved AFAIK, It has a big bug. Fix it and your PR will be accepted after the testing 😄 
 If you have discord ping me || Mr.Minnu#1031 ||

2021-10-14 15:15 UTC, jxstxn1 commented
> @jxstxn1 Sorry to tell you, this cannot be approved AFAIK, It has a big bug. Fix it and your PR will be accepted after the testing 😄

Yes Im fixing the AppTheme bug right now.
If there are any more bugs tell me

2021-10-14 15:16 UTC, yahu1031 commented
> > @jxstxn1 Sorry to tell you, this cannot be approved AFAIK, It has a big bug. Fix it and your PR will be accepted after the testing 😄
> 
> Yes Im fixing the AppTheme bug right now. If there are any more bugs tell me

yes there is. i can't record it(I don't have good app). Ping me in discord or Twitter(find in my profile)

2021-10-14 15:29 UTC, jxstxn1 commented
> > > @jxstxn1 Sorry to tell you, this cannot be approved AFAIK, It has a big bug. Fix it and your PR will be accepted after the testing 😄
> > 
> > 
> > Yes Im fixing the AppTheme bug right now. If there are any more bugs tell me
> 
> @jxstxn1 yes there is. i can't record it(I don't have good app). Ping me in discord or Twitter(find in my profile)

I pinged you on twitter

2021-10-14 16:01 UTC, yahu1031 commented
@jxstxn1  The issue is, It builds the UI but it keeps shivering. IDK why?. When I hover, it shows loading hover overall the app and it overlays on all apps. Nothing can be able to do with it. Just run and stop the app. That's it. Better you run the app once.
![image](https://user-images.githubusercontent.com/35523357/137354550-b10529b4-b3d1-4ab0-b1c0-fa8f90affffc.png)

2021-11-04 10:05 UTC, YazeedAlKhalaf commented
I am sorry, but I don't have time to review the changes. They are a lot and need a lot of time.

2021-11-04 11:00 UTC, yahu1031 commented
> I am sorry, but I don't have time to review the changes. They are a lot and need a lot of time.

@YazeedAlKhalaf  LOL, I can handle it but need a fix. This PR is not so stable. It is still buggy. I asked him to check it.

2022-01-06 04:09 UTC, YazeedAlKhalaf commented
@jxstxn1
This PR has been sitting here for more than 2 months, I will close it for now but if you can enhance it or split it, it will be great.
Thanks a lot!

2022-01-06 04:09 UTC, closed without merging